### ISSUE TITLE
npp-user-manual.org shows an empty page if accessed with IPv6

### ISSUE THREAD

**Issue by justanotheranonymoususer** [notepad-plus-plus/npp-usermanual#132]
![image](https://user-images.githubusercontent.com/5781692/99151499-493a9480-26a4-11eb-9b06-d341813eb735.png)

**Comment by pryrt** [comment]
It's working for me.  Is it still broken for you?

**Comment by justanotheranonymoususer** [comment]
Yes, still broken

**Comment by justanotheranonymoususer** [comment]
Maybe because I have internet with IPv6 support. Try this:
http://www.ipv6proxy.net/go.php?u=http%3A%2F%2Fnpp-user-manual.org%2F&b=0&f=norefer

**Comment by pryrt** [comment]
It still works for me.

![image](https://user-images.githubusercontent.com/17455758/99159726-22746200-2694-11eb-98e8-66cbdeb505f1.png)

**Comment by justanotheranonymoususer** [comment]
Works for me now too on ipv6proxy, but not on my computer

**Comment by justanotheranonymoususer** [comment]
Here's the IP I'm getting if that helps:

![image](https://user-images.githubusercontent.com/5781692/99159811-e1f30380-26e8-11eb-9ecf-950d18dba41b.png)

**Comment by justanotheranonymoususer** [comment]
I can also reproduce it here: https://www.ip6on.ly/

![image](https://user-images.githubusercontent.com/5781692/99160238-c4746880-26ed-11eb-9547-9b3171515462.png)

**Comment by pryrt** [comment]
I have no access to the server -- I am just one of the content maintainers.

The symptoms described seem to indicate that the host for npp-user-manual.org uses a round-robin approach, and some of its underlying systems aren't configured to properly serve the correct content.  But that's just a guess, because I don't know who the host is, or how it's configured under the hood.

@donho will have to step in,

**Comment by justanotheranonymoususer** [comment]
OK, thanks, at least you no longer think I'm crazy =)

**Comment by pryrt** [comment]
@donho , per https://community.notepad-plus-plus.org/topic/20321/user-manual-is-gone, it looks like more users are noticing this (or a similar) problem. 

If the usermanual website host has a round-robin system, one of the robins may be misconfigured; if not, something else is going wrong that is creating an intermittent issue.

**Comment by donho** [comment]
@pryrt OK, I'll check it.

**Comment by donho** [comment]
@pryrt  @justanotheranonymoususer 
I just checked again and it work (without doing anything).

![image](https://user-images.githubusercontent.com/90293/99744512-20693380-2ad8-11eb-862d-4435ac66d44b.png)

**Comment by justanotheranonymoususer** [comment]
@donho it sometimes works and sometimes doesn't. Click on the website multiple times:

![EmKyucvgLD](https://user-images.githubusercontent.com/5781692/99782133-6d252c80-2b21-11eb-90ed-cc5d3dc262cb.gif)

**Comment by donho** [comment]
I'm reproducing this issue now:

![image](https://user-images.githubusercontent.com/90293/103294473-341a8a80-49f2-11eb-8932-7ab7f3ca0465.png)

**Comment by donho** [comment]
@pryrt 
> The symptoms described seem to indicate that the host for npp-user-manual.org uses a round-robin approach, and some of its underlying systems aren't configured to properly serve the correct content. That might explain why some of those ipv6 proxies show the right content and others don't, or that they change over time.

How can I check it?

**Comment by pryrt** [comment]
@donho ,

Unfortunately, I am not an expert.  I know that with IPv4, if you have the same domain name mapped to multiple IP addresses (["round robin"](https://en.wikipedia.org/wiki/Round-robin_DNS)), then the end user will be randomly connected to one of the IP addresses; so if one of machnies behind those IP addresses is configured differently, you can get different results.  I assume something similar is possible with IPv6.

(Note that this is in the DNS settings for the domain, not in the webserver itself, though those settings may be on the same machine, depending on domain registrar (which usually handles DNS) vs webhost.)

When I run nslookup from my desktop, I get
```
C:\Users\Peter>nslookup npp-user-manual.org
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    npp-user-manual.org
Addresses:  2a02:4780:8:362:0:2b37:d7f5:3
          2a02:4780:1:1::1:920b
          31.220.49.230

C:\Users\Peter>nslookup wingup.org
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    wingup.org
Address:  31.220.49.230
```
It looks like there are two possible IPv6 addresses for npp-user-manual.org and one IPv4 -- though the IPv6 are different lengths, and I'm not sure what that means (again, not an IPv6 expert).  Whereas wingup.org appears to only be associated with a single IPv4.

So, since it appears the domain maps to two IPv6, I am assuming one of those two is behaving differently than the other.

**Comment by donho** [comment]
It seems to me that it was due to the SSL certificate deploying problem.
The certificate on https://npp-user-manual.org/ changes every 2 months so the problem has gone.
It could happen again though. If anyone experience the same problem, please ping me here, then the issue will be reopened and I will investigate it.
