### ISSUE TITLE
Building a lexer plugin

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/npp-usermanual#137]
From what I see, documentation on how to build a lexer plugin is missing.
Is there something in the pipeline or should I start writing one?

**Comment by pryrt** [comment]
I don't know of anyone who is working on that.  

I would love to have that process documented _somewhere_.  I just don't know if that's something that should be in the main usermanual website... We've been trying to not overwhelm readers with big complex pages in the manual -- that said, the searching and plugin communication pages are both pretty big and detailed.  So it's hard to say.

If it was no longer than the "[How to develop a plugin](https://npp-user-manual.org/docs/plugins/#how-to-develop-a-plugin)" overview that's currently there, then adding it to the manual is easily justifiable, as it would be another section in that same page.  

But my guess is that, to do a good job, it would need to be fairly detailed (and require its own page).  

Because of that, and since it would be more of a "tutorial" or "howto", rather than documenting behavior and features, I would lean toward saying that the Forum is a better location -- either a pinned post in Plugins Development, or as a FAQ Desk entry (ala MAPJe71's Function List Basics, which takes some of the ideas that are in the Function List and Config File docs, but presents them in more of a tutorial/howto manner)

For now, I am assigning this task to @Ekopalypse .  If one of the other usermanual admins was already working on that, feel free to re-assign it to yourself.  

And I'd welcome other opinions on whether this documentation would fit better in the usermanual, or as a Community post / FAQ of some sort.

**Comment by Ekopalypse** [comment]
Actually I don't think this should be a tutorial, as this can never cover all languages that can be used to write a lexer plugin.
An overview of what needs to be done and where to find the necessary information should be sufficient in my opinion. 
My idea had been to list and briefly explain the additional functions, as well as the necessary XML file. That was it already. I think without XML example file ~1-2 pages.

I wait a couple of days to see if there are other opinions before I begin with this.

**Comment by pryrt** [comment]
Ah, okay.  That sounds much more like what I would expect in the manual itself.

**Comment by pryrt** [comment]
Inspired by the [recent forum discussion](https://community.notepad-plus-plus.org/topic/20689/basic-language-and-folding-questions), it might be nice to include in this overview whether or not it's possible to take the source code for one of the builtin lexers, and easily convert it into a plugin lexer, and thus be able to extend an existing lexer to add your own highlighting or folding (so that they don't have to start from scratch).  I don't know how much overhead is needed to make a lexer.cpp compatible with a plugin-style lexer, but it would be something to point people toward.

**Comment by Ekopalypse** [comment]
From the point of view of creating a lexer plugin, it makes no difference whether you start from scratch or use a built-in lexer. The interface must be respected, and this is easier to do with some built-in lexers that already do this than with others that were not created with this in mind.
