### ISSUE TITLE
Add "Mute All Sounds" preference [v7.9.4]

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#169]
v7.9.4 added **MISC > [Mute All Sounds](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7950)**, so needs to be added to preferences.md and mentioned in searching.md's (search for "Volume Mixer" for the right place)

@sasumner , did you want this one, because it was your PR?  If not, feel free to assign it to me, instead.

**Comment by sasumner** [comment]
>because it was your PR?

Not my PR.  In fact, I have no contributions at all to 7.9.4.  :-(
I thought @mere-human already changed the docs for the "sounds" stuff.

**Comment by mere-human** [comment]
This has been already addressed in https://github.com/notepad-plus-plus/npp-usermanual/pull/161

**Comment by sasumner** [comment]
Final thoughts to @pryrt :

I like the idea of prompting the authors of N++ code changes to do the documentation updates.
No one understands all of the implications from a change as well as the original author, so that's where the best documentation will arise from.
In other words, keep doing exactly what you did here, in the future.

**Comment by pryrt** [comment]
Sorry, I saw you as a first response to the issue, and you had handled all the volume stuff in earlier versions, so my mind automatically assumed that you were the one that handled the mute in the end.  

As to why I hadn't remembered (or didn't see) that it had already been addressed -- I guess when I checked, I accidentally looked at the live website rather than the most recent versions in the repo.
