### ISSUE TITLE
Convert "Search results Window" into separate chapter

### ISSUE THREAD

**Issue by Uhf7** [notepad-plus-plus/npp-usermanual#176]
I have a little problem here with the structure of the manual. It regards the chapter "searching".

As it is now:

Searching
- Dialog based searching
  - Find / Replace
  - Find in Files
    with a large sub-section "Search results" window
  - Find in Projects
  - Highlighting and Bookmarking
- Dialog-free search/mark actions
  - Searching
  - Highlighting
- Finding characters in a specific range
- Incremental Search  ...
   ...

Within the sub-chapter "Find in Files" there is embedded a long section about the ""Search results" window".  This section is important, and it actually applies now to two higher-ranking sections, "Find in Files" and "Find in Projects". 

So my proposal is here to move the section ""Search results" window" into an own chapter, at the same level with "Dialog-based Searching", "Dialog-free search/mark actions", and "Finding characters in a specific range".

As it should be:

Searching
- Dialog based searching
  - Find / Replace
  - Find in Files
  - Find in Projects
  - Highlighting and Bookmarking
- "Search results" window
- Dialog-free search/mark actions
  - Searching
  - Highlighting
- Finding characters in a specific range
- Incremental Search  ...
   ...

Please tell me, if there is anyone out there who feels the same way ...

**Comment by pryrt** [comment]
Given that the results window can apply to **Find/Replace**, **Find in Files**, and now **Find in Projects**, it makes sense to me to move it out from under **Find/Replace**.  

But, since the **"Search Results" Window** is a result of the Dialog-based searching, maybe it should be a fifth subsection section, rather than an independent main section:
* Dialog based searching
    * Find / Replace
    * Find in Files
    * Find in Projects
    * Highlighting and Bookmarking
    * "Search results" window

... but I'm not heavily invested either way, and I understand the counter-argument that "Search results" is not one of the tabs on the main dialog, whereas the other four sub-sections are.  

So I'd be fine with either making it the fifth subsection (inside **Dialog based searching**), or making it the second main section (after **Dialog based searching**).

@sasumner was heavily involved in the GUI portions of the searching.md page, so getting his opinion would be good.

**Comment by sasumner** [comment]
@pryrt 

Thanks for asking my opinion.

I agree that it deserves its own section, either as a "fifth" point of dialog-based searching, or as more of a "main" searching section.  It makes sense either way; perhaps I have a slight leaning towards not making it a 5th point.

**Comment by Uhf7** [comment]
To make it better fit as 5th point under Dialog-based searching, we could change the titles of the first four points, so that it looks like this:

- Dialog based searching
  - Find / Replace tabs
  - Find in Files tab
  - Find in Projects tab
  - Mark tab
  - Search Results window

**Comment by pryrt** [comment]
@Uhf7 ,  are you still interested in doing this one?  If you're going to want it in the manual published right after v8, it will need to be submitted soon.  (Normally, the usermanual goes out about a week after the full release; the release candidate was just announced.)

**Comment by Uhf7** [comment]
I think it was done with PR #182. I close the issue.

**Comment by pryrt** [comment]
You're right.  I just saw the issue still open, and forgot the PR had been submitted and merged.
