### ISSUE TITLE
Document reverse line order feature

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/npp-usermanual#216]
References:

* https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ddd4448192f8dcbc72accb20a0a077dbdfc27c21
* https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9839 "Add ability to reverse line order"
* https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9837 "[Feature request] Reverse line order"

**Comment by debiedowner** [comment]
Will do, once the feature makes it into release.

Or maybe I can add it earlier? But I figured adding it might be confusing if next version takes long to release; also it seems I need to mention the version it was added, I don't know if I can assume it will be called 7.9.6. It looks like some dark theme stuff is coming, so maybe it will have a more major release name instead?

I probably should have gone ahead and added it anyway instead of writing this comment as it would be much shorter :) Anyway, I'll remember to do it.

**Comment by sasumner** [comment]
@debiedowner 

>Or maybe I can add it earlier?

Go for it! :-)
You do not have to wait for it to "make it into release".
The user-manual release person won't release a new manual until the appropriate time.

We typically add some words referring to the release it is in, in the manual entry, example:
"feature xxx is yyy (available in v7.9.6 and later)"

>if I can assume it will be called 7.9.6

If this changes the manual release person will alter it later.
You can assume 7.9.6.

**Comment by debiedowner** [comment]
Oh, I mistakenly thought that the manual was just a Github Page for this repo, so anything merged would go live immediately; that's why I was wary of making a change prematurely. I now realize that it is separately generated using Hugo. I am making a pull request now.
