### ISSUE TITLE
Option to allow replacing a sequence of characters by a line break should be documented

### ISSUE THREAD

**Issue by maettu-this** [notepad-plus-plus/npp-usermanual#344]
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11494.

**Comment by pryrt** [comment]
It _is_ documented.

The section "Substitution Escape Sequences" (https://npp-user-manual.org/docs/searching/#substitution-escape-sequences) says "In substitutions, in addition to allowing the [Control Characters](https://npp-user-manual.org/docs/searching/#control-characters), [Non ASCII characters](https://npp-user-manual.org/docs/searching/#non-ascii-characters), and [Character escape sequences](https://npp-user-manual.org/docs/searching/#character-escape-sequences) from search expressions, the following additional escape sequences are recognized:" -- and the [Control Characters](https://npp-user-manual.org/docs/searching/#control-characters) section linked in that sentence shows how to to indicate a newline character:
> ![image](https://user-images.githubusercontent.com/17455758/162287469-4e423181-94a4-4393-8f9b-c66fdc37fa82.png)

And if you were curious how to match the literal `\` in your original text in the FIND expression, you could look at the [single character matches](https://npp-user-manual.org/docs/searching/#single-character-matches) section, where it explains that you put a backslash before a special character to make it literal:
> ![image](https://user-images.githubusercontent.com/17455758/162287811-e237b37c-3baf-4397-94a2-53a24584c273.png)

In the other post, you also say,
> Also, what confuses me with the `Replace` dialog:
> * Why is `Backward direction` greyed out when using `Regular expression`? `Wrap around` is active.

Searching for "backward" in the Searching document leads you to the introductory paragraphs of [Regular Expressions](https://npp-user-manual.org/docs/searching/#regular-expressions), which says, "Note: Starting in v7.8.7, regex backward search is disallowed due to sometimes surprising results. If you really need this feature, please see [Allow regex backward search](https://npp-user-manual.org/docs/preferences/#preferences-for-advanced-users) to learn how to enable this option."

So that feature of Notepad++ is also documented.

> * `.` matching newline seems a very particular behavior when being used to regular expression.

In [Find/Replace Tabs](https://npp-user-manual.org/docs/searching/#find-replace-tabs) it describes this behavior in the **☐ . matches newline** bullet item.  Moreover, it explains that it is equivalent to the `(?s)` and `(?-s)` regular expression syntax.  A historical lesson for you, that doesn't belong in the manual; that .-matches-newline behavior was part of the original Boost regular expression engine, which itself derived from [PCRE](# "Perl Compatible Regular Expression syntax"), which is derived from early Perl regular expression notation.  All of those go back to the idea that sometimes when you are searching a whole document, you want the `.` wildcard to always stay on a single line (so `(?s)` is disabling .-matches-newline, equivalent to Perl's `/s` modifier or `(?s)` syntax) and sometimes you want the `.` wildcard to be able to match every character including a newline (so `(?-s)` being equivalent to enabling .-matches-newline).  But that history lesson isn't necessary in a User Manual; and the**☐ . matches newline** checkbox behavior _is_ documented and that documentation explains the exact behavior of this regular expression syntax.

Every one of your points is already documented in the User Manual.  Unfortunately, it's a long document, and regular expressions are hard to wrap your head around in the beginning.  The only way to learn them is to read about them and experiment, then repeat _ad infinitum_ until you are more comfortable.  I personally have been using regular expressions since I started using `vi` in college in the 90s, and throughout my use of `vi` and Perl and Notepad++ over the decades since then, and I still have to frequently refer to the documentation to see the intricate behavior.  

The User Manual isn't meant to be a full regular expression tutorial with a deep dive of every piece of regex syntax ... though to my knowledge, it does _mention_ every piece of syntax and all the options in the Find/Replace/etc dialogs.  If you want more on regular expressions, the User Manual _does_ link to the Boost library regular expression documentation (for both the FIND and the REPLACE), which is the canonical reference for the Boost regex engine which Notepad++ uses, and might explain things in a different way, which may help you understand things better.  And for more generic information on regular expressions, the internet abounds with advice: the [Notepad++ Community Forum](https://community.notepad-plus-plus) (which @alankilborn already linked you to) has a FAQ entry on [where to find regular expression documentation](https://community.notepad-plus-plus.org/topic/15765/faq-desk-where-to-find-regular-expressions-regex-documentation), with a link to the user manual, and links to a plethora of other useful sites.

Unless you can point to a specific syntax which isn't documented, I will be closing this issue soon.

**Comment by alankilborn** [comment]
So your example is that you have this literal text in a N++ tab: `123\r\nABC\r\nXYZ`
And you want to convert it to this via replacement:

    123
    ABC
    XYZ

So you could use Extended mode to search for: `\\r\\n` and replace with `\r\n`.
This uses `\\` (documented [HERE](https://npp-user-manual.org/docs/searching/#:~:text=the%20literal%20backslash%20character)) and `\r` (documented [HERE](https://npp-user-manual.org/docs/searching/#:~:text=The%20Carriage%20Return%20control%20character%20CR)) and `\n` (documented [HERE](https://npp-user-manual.org/docs/searching/#:~:text=the%20Line%20Feed%20control%20character%20LF)).

Or you could use Regular-expression mode to search for: `\\r\\n` and replace with `\r\n`.
This uses `\\` (documented [HERE](https://npp-user-manual.org/docs/searching/#:~:text=This%20allows%20you%20to%20search%20for%20a%20literal%20character)) and `\r` (documented [HERE](https://npp-user-manual.org/docs/searching/#:~:text=The%20CR%20control%20character%200x0D)) and `\n` (documented [HERE](https://npp-user-manual.org/docs/searching/#:~:text=The%20LF%20control%20character%200x0A)).

The only real deficiency I see in the docs might be for [this link](https://npp-user-manual.org/docs/searching/#:~:text=This%20allows%20you%20to%20search%20for%20a%20literal%20character) for regex, in terms of not specifically calling out `\\`.  Maybe this should be made more specific?

**Comment by pryrt** [comment]
>  in terms of not specifically calling out \\. Maybe this should be made more specific?

Do I really have to re-list all the special characters in that paragraph?  It already tells you to use that syntax for any character that has another meaning in the regex syntax.

**Comment by alankilborn** [comment]
>Do I really have to re-list all the special characters in that paragraph?

Nope, I said _maybe_. :-)
But, traditionally, other documentation of this ilk goes out of its way to identify `\\` specifically, so _maybe_ N++ should as well.
I'm certainly fine with it the way it is, just trying to put myself in the head of the noobs.

**Comment by pryrt** [comment]
I'm thinking the new phrasing will be:
> * `\$`,`\(`,`\)`,`\*`,`\+`,`\.`,`\?`,`\[`,`\]`,`\\`,`\|`  ⇒ The characters `$()*+.?[]\|` all have special meaning to the regex engine; to get them to match as a literal (or to show up as a literal in the substitution), you will have to prefix them with the `\` character.  Prefixing with `\` to "escape" the character allows you to search for a literal character when the regular expression syntax would otherwise have that character have a special meaning as a regex meta-character. There are also other characters which are special only in certain circumstances (any time a charcter is used in a non-literal sense  throughout the Regular Expression section of this manual); any of those will have to be "escaped" by putting a `\` before it if you want it to be treated as a literal instead of the special character _in those situations_.  

(And here's hoping `\[` won't bite me in the user-manual backend conversion like it does in the forum)
