### ISSUE TITLE
Some messages and notifications are missing

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/npp-usermanual#42]
List of messages and notifications which aren't documented yet
NPPM_ADDTOOLBARICON
NPPM_DECODESCI
NPPM_DISABLEAUTOUPDATE
NPPM_DMMVIEWOTHERTAB
NPPM_DOCSWITCHERDISABLECOLUMN
NPPM_ENCODESCI
NPPM_GETCURRENTVIEW
NPPM_GETEDITORDEFAULTBACKGROUNDCOLOR
NPPM_GETEDITORDEFAULTFOREGROUNDCOLOR
NPPM_GETENABLETHEMETEXTUREFUNC
NPPM_GETFILENAMEATCURSOR
NPPM_GETNBUSERLANG
NPPM_GETNPPFULLFILEPATH
NPPM_GETPLUGINHOMEPATH
NPPM_MAKECURRENTBUFFERDIRTY
NPPM_REMOVESHORTCUTBYCMDID
NPPM_SAVEFILE
NPPM_SAVESESSION
NPPM_SETEDITORBORDEREDGE
NPPM_SETSMOOTHFONT
NPPM_SETSTATUSBAR

NPPN_BEFORESHUTDOWN
NPPN_CANCELSHUTDOWN
NPPN_FILEBEFOREDELETE
NPPN_FILEBEFORERENAME
NPPN_FILEDELETED
NPPN_FILEDELETEFAILED
NPPN_FILERENAMECANCEL
NPPN_FILERENAMED
NPPN_READONLYCHANGED
NPPN_SNAPSHOTDIRTYFILELOADED

**Comment by Ekopalypse** [comment]
Q: Is it assumed that I do a PR for each of the missing messages/notifications or
can I create one PR for all?

**Comment by pryrt** [comment]
A: just do the one PR for a family of similar changes

**Comment by Ekopalypse** [comment]
You mean one PR for messages and one for the notifications?

**Comment by pryrt** [comment]
Just one total is fine.

If you were editing multiple docs for unrelated reasons, that would be multiple PR.  But if it's all edits to the same doc, it's easier for everyone for one PR

**Comment by Ekopalypse** [comment]
Another Q: 
NPPM_ messages do have a space between each message.
For me this looks much more readable than the notifications which are "glued" together.
Should we add an additional spacing to each notification as well?

**Comment by pryrt** [comment]
Go ahead.  (I don't think it needs the space to be readable, but don't have a strong opinion against the space.  And consistency is probably a good idea.)

**Comment by pryrt** [comment]
I tend to agree with @pnedev in the forum, in that they were probably marked as "internal" for a reason.  It might be nice to _know_ the reason, but because they aren't part of the public API for plugin messages, they don't need to be documented.  (I didn't realize at the time that the internal messages were from a different header file.)

**Comment by Ekopalypse** [comment]
Just wanted to comment on the forum post but I agree too, only official API should be documented.
From my limited understanding about API design - you keep your internal implementation hidden to 
be as flexible as possible. If there is a need to redesign something, you just have to take care that this is transparent to the official API.

**Comment by Ekopalypse** [comment]
@pryrt 

would you mind having a look at https://github.com/Ekopalypse/npp-usermanual/blob/more_messages_and_notifications/content/docs/plugin-communication.md

I added a few things on the introduction, then I added a table
which explains the table layout used by the following messages.
Note, the new layout starts with the message NPPM_ADDTOOLBARICON.
The current layout is used for comparison.

There are two issues which I'm unsure how to handle.
1st. the table doesn't use the whole width always.
I tried setting different width values but without getting the expected result.
Do you have any idea?

2nd. What should be done regarding the documentation and the two open npp issues? See TODO ...

In general, the layout is still a bit messy - see, for example, NPPM_DMMREGASDCKDLG and NPPM_GETNBOPENFILES
compared to most of the others.
Btw. should we use normal text style to inform about the messages and notifications?
Meaning ending a sentence with a dot and starting with a uppercase letter etc...?

Anything else?

Thank you

**Comment by pryrt** [comment]
1. Table width = I noticed that too while doing my updates to that page, but I don't think it's real.  Did you download the Hugo app (extended version) from the link in the repo's README?  When I rendered my edits with that, rather than with GitHub's rendering engine, the table widths came into line.  (GitHub and Hugo use different flavors of markdown engines, so it's probably a processing difference between the two; or a stylesheet difference.)

   * I'm wondering whether the presence or lack of `<TBODY>` is influencing it: the old-style uses the TBODY whereas your new ones don't, and your new ones render with the gap to the side of the table in GitHub (haven't downloaded your version to try in Hugo, sorry).
   * I do like your conversion from `wParam: | [in] desc` to `in | desc`, because it avoids repeating the headers for every entry.

2. Regarding open issues: documentation should match what's currently there.  When the change gets implemented, documentation should be updated to match.

3. Messy: some of them just have more complicated info that needs to be communicated.  I like the compact table-layout for the NPPM_GETNBOPENFILES (except that the header rows got stripped to text on individual lines; that should be fixed)... but I'm not sure whether the structures in NPPM_SAVESESSION and NPPM_DMMREGASDCKDLG would really work better as a table or left as-is.

4. Periods and capitals: Statements/sentences should definitely start with uppercase.  I'm less certain about periods at the end, as I often forget them in the more bullet-style of prose prevalent throughout the documentation.  If you were to add periods to them all, I wouldn't complain.  (If you removed all the periods, I probably would complain.)  Probably best to use periods.

**Comment by Ekopalypse** [comment]
Yes, I'm using Hugo extended locally to see how it renders, but it seems it is random behavior.
For example see this screenshot

![image](https://user-images.githubusercontent.com/47723516/67239128-0c1eb700-f43e-11e9-97b7-4c788582523c.png)

and now compare with this one

![image](https://user-images.githubusercontent.com/47723516/67239194-35d7de00-f43e-11e9-8975-f9c9a1fb376e.png)

I don't get it.

Concerning tbody, my understanding is that it is not needed but if used it should be used with thead and tfoot.

I'm open for any suggestion, even one which starts with _**"get rid of inline html ..."**_

**Comment by pryrt** [comment]
Weird.  When I render with hugo in Chrome for 
```
<table border="1" width="100%">
<tbody>
<tr>
<td width="50%" rowspan="2" style="background:LightYellow;">  NPPM_GETBUFFERLANGTYPE
</td>
<td width="10%" style="background:khaki"> wParam:
</td>
<td width="30%" style="background:SeaShell;"> 0
</td></tr>
<tr>
<td width="10%" style="background:khaki"> lParam:
</td>
<td>  0
</td></tr>
<tr>
<td colspan="3" style="background:#E8F8E8;">  Get document's language type from given buffer ID.
<p>Returns value&nbsp;: if error -1, otherwise language type (see LangType).
[in] int bufferID
</p>
</td>
</tr>
</tbody></table>

<table border="1" width="100%">
<tbody>
<tr>
<td width="50%" rowspan="2" style="background:LightYellow;">  NPPM_SETBUFFERLANGTYPE
</td>
<td width="10%" style="background:khaki"> wParam:
</td>
<td>  [in] int bufferID
</td></tr>
<tr>
<td width="10%" style="background:khaki"> lParam:
</td>
<td>  [in] LangType langType2Set
</td></tr>
<tr>
<td colspan="3" style="background:#E8F8E8;">  Set language type of given buffer ID's document.
<p>Returns TRUE on success, FALSE otherwise.
L_USER and L_EXTERNAL are not supported.
</p>
</td>
</tr>
</tbody></table>
```
I get 
![image](https://user-images.githubusercontent.com/17455758/67248393-30b46800-f419-11e9-8242-7ed6789cde1c.png)

Even when I add the 30% and SeaShell to the lparam,
```
<table border="1" width="100%">
<tbody>
<tr>
<td width="50%" rowspan="2" style="background:LightYellow;">  NPPM_GETBUFFERLANGTYPE
</td>
<td width="10%" style="background:khaki"> wParam:
</td>
<td width="30%" style="background:SeaShell;"> 0
</td></tr>
<tr>
<td width="10%" style="background:khaki"> lParam:
</td>
<td>  0
</td></tr>
<tr>
<td colspan="3" style="background:#E8F8E8;">  Get document's language type from given buffer ID.
<p>Returns value&nbsp;: if error -1, otherwise language type (see LangType).
[in] int bufferID
</p>
</td>
</tr>
</tbody></table>

<table border="1" width="100%">
<tbody>
<tr>
<td width="50%" rowspan="2" style="background:LightYellow;">  NPPM_SETBUFFERLANGTYPE
</td>
<td width="10%" style="background:khaki"> wParam:
</td>
<td width="30%" style="background:SeaShell;">  [in] int bufferID
</td></tr>
<tr>
<td width="10%" style="background:khaki"> lParam:
</td>
<td>  [in] LangType langType2Set
</td></tr>
<tr>
<td colspan="3" style="background:#E8F8E8;">  Set language type of given buffer ID's document.
<p>Returns TRUE on success, FALSE otherwise.
L_USER and L_EXTERNAL are not supported.
</p>
</td>
</tr>
</tbody></table>
```
I get 
![image](https://user-images.githubusercontent.com/17455758/67248497-87ba3d00-f419-11e9-854b-3cc6ee127d0c.png)

So I don't know why yours is rendering differently.  Different browser, maybe?

\-----
> ... tbody ...

I know it's not required, but I thought maybe it was affecting the rendering engine in some subtle way.

> "get rid of inline html ..."

I'd be more tempted to "switch from .md to .html", but I don't really like that idea (I think hugo can handle mixed media in the different files, but haven't tried it).

These subtle issues are why I went with "good enough to get the content across", rather than "wow, that's all consistent and looks great".  

Maybe starting over with an inline-html table structure that's more consistent, and uses classes for styling the td rather than manual `width` and `style` attributes.  But I don't know if that would solve it.

Sorry I'm not more help on this part.

**Comment by Ekopalypse** [comment]
Thank you very much for your time and thoughts about this.

>So I don't know why yours is rendering differently. Different browser, maybe?

Yes, you are right and I did some more tests and it seems the current solution is not only rendered differently by using different browsers but also by different display resolutions. 
And by that I don't mean some nasty little 100x100, but, on my main display I have 1920x1080 whereas my second monitor, which I'm using to view the results, is having 1280x1024 and it looks way better, not perfect, on the main display as on the second display. 
Webpage was loaded full screen.

>Maybe starting over with an inline-html table structure that's more consistent, and uses classes for 
>styling the td rather than manual width and style attributes. But I don't know if that would solve it.

Haha, that's what I thought yesterday as well and I'm using currently something like

```
<style>
/* table layout*/
table {
  table-layout: fixed;
  width: 100%;
  border: 1px solid black;
}

tr {
  width: 100%;
}

/* Message columns are based on these configurations */
td.nppm {
  width: 50%;
  background:LightYellow;
}
td.inout {
  width: 10%;
  background: khaki;
  text-align: center;
}
td.wparam {
  width: 40%;
  background:SeaShell;
}
td.lparam {
  width: 40%;
}
td.nppm_desc {
  width: 100%;
  background: #E8F8E8;
}

/* Notification columns are based on these configurations */
td.nppn {
  width: 90%;
  background:LightYellow;
}
td.hwndFrom {
  width: 20%;
}
td.idFrom {
  width: 20%;
  background:SeaShell;
}
td.nppn_desc {
  width: 100%;
  background: #E8F8E8;
}
</style>

<table>
<tr>
<td rowspan="2" class="nppm">Message</td>
<td class="inout">in</td>
<td class="wparam">wParam</td>
</tr>
<tr>
<td class="inout">inout</td>
<td class="lparam">lParam</td>
</tr>
<tr>
<td colspan="3"  class="nppm_desc">Description</td>
</tr>
</table>
```

didn't solve the issue but makes further changes easier to implement :-)

I guess I'm creating a pure html solution to see when it starts to break, to get a better
understanding what is going on.

**Comment by pryrt** [comment]
@Ekopalypse , I saw your [forum mention](https://community.notepad-plus-plus.org/post/53935).  Yes, HTML should be fine; as long as it renders reasonable using `hugo`, it should be good.  (I wish I knew why the markdown wasn't allowing consistent column widths, but it's more important to have the documentation.)

**Comment by Ekopalypse** [comment]
@pryrt - I tried again solving it by using pure markdown.
What do you think about this

![image](https://user-images.githubusercontent.com/47723516/82495331-75e96700-9ada-11ea-958c-a11cede8feed.png)

I think the first one doesn't look modern but has a clean layout.
The second one, still not fancy but maybe a bit more modern.

What do you think?

**Comment by Ekopalypse** [comment]
From maintenance point of view it seems that the second one is better

![image](https://user-images.githubusercontent.com/47723516/82497125-4b4cdd80-9add-11ea-97fb-b46f1565efba.png)

**Comment by pryrt** [comment]
I don't think having the primary information conveyed in preformatted text blocks is the way to go, so I don't like the first.

I would vote for the second.  It seems reminiscent of ~MSDN~ Windows Dev Center documentation ([example](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessage)), but does a better job of conveying header-vs-description than MS.  And it will be easier to maintain than the table format.

**Comment by Ekopalypse** [comment]
Ok, thank you - I'll go for it

**Comment by Ekopalypse** [comment]
The notification are sorted but the messages are not which makes them difficult to find,
maybe we should sort the messages too?

**Comment by pryrt** [comment]
Sorted does make more sense, unless they are already grouped thematically rather than alphabetically.  Would you like to take it on and do another PR, or would you prefer I take it on?

**Comment by Ekopalypse** [comment]
I can make another PR, no problem.
