### ISSUE TITLE
Line Number Show/hide

### ISSUE THREAD

**Issue by tomm174** [notepad-plus-plus/npp-usermanual#537]
First : Thanks for what you do, NPP is a real asset.

I think however the info on how to show/hide line-numbers has fallen between the cracks.
The documentation of the location of the show/hide line-numbers toggle no longer matches the software.

The documentation at
https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/docs/preferences.md
says as follows:
"_Line number margin [background and foreground] ⇒ If Line Number > Display is checked in [Preferences > Margins/Border/Edge](https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/docs/preferences.md#margins-border-edge), this sets the style for those line numbers. The "Go to settings" link will take you to [Preferences > Margins/Border/Edge](https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/docs/preferences.md#margins-border-edge) so you can change Line Number settings._"

However in my copy of the software (Ver 8.5.4, updated today), the line number toggle is not present at this setting (Preferences > Margins/Border/Edge).

I've followed the links in the documentation, and carried out extensive googling to no avail. Perhaps the problem is just in the documentation, or possibly the functionality has been removed from one place with the intention of putting it somewhere else, but this hasn't happened.

I'd fix the problem if I could, but I fear that is beyond me, I'd be very appreciative of either a documentation or a software update to be able to access the toggle. 
Thanks

PS - There seems no very obvious reason why both the documented locations shouldn't do the job (the other was in Settings/Editing). 
Redundant options abound in UI & seem generally useful.

**Comment by pryrt** [comment]
> The documentation of the location of the show/hide line-numbers toggle no longer matches the software.

Yes it does.

>  the line number toggle is not present at this setting (Preferences > Margins/Border/Edge).

Yes it is.  Here are screenshots showing my **Settings > Preferences > Margins/Border/Edge** status for the **Line Number  > Display** entry, along with the Debug Info showing that the screenshot was taken in v8.5.4, along with showing where the line numbers are or are not, depending on the setting.  I added big arrows next to the setting and to the resulting line number in Notepad++ itself.

| setting | image | results
|---|---|---
| ☑ checkmarked | ![image](https://github.com/notepad-plus-plus/npp-usermanual/assets/17455758/e17ec8f8-901c-4b88-a864-b73e5ba12b23) | line numbers shown
| ☐ not checkmarked | ![image](https://github.com/notepad-plus-plus/npp-usermanual/assets/17455758/a24407b6-80eb-47df-9102-41cd311e88f7) | line numbers not shown

It is _exactly_ where the User Manual describes it as being.

> There seems no very obvious reason why both the documented locations shouldn't do the job (the other was in Settings/Editing).

As the manual [states](https://npp-user-manual.org/docs/preferences/#:~:text=Line%20Number%3A,document%20(new%20to%20v7.9.2))
| |
|---|
| ![image](https://github.com/notepad-plus-plus/npp-usermanual/assets/17455758/3e2e6d2b-bef1-4953-b285-1fe6c2bfd63c) |
... it was renamed and move in v7.9.2.  It used to be in **Settings > Preferences > Editing**.  Starting in v7.9.2 (and still true today in v8.5.4) it is in **Settings > Preferences > Margins/Border/Edge**.  So it's been in the "new" location since January 2021.
