### ISSUE TITLE
Regex: (*SKIP) and similar

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#595]
The [Backtracking Control Verbs](https://www.boost.org/doc/libs/1_80_0/libs/regex/doc/html/boost_regex/syntax/perl_syntax.html#boost_regex.syntax.perl_syntax.backtracking_control_verbs) are never mentioned in the User Manual.  

I will probably just copy over the Boost descriptions into our User Manual.

**Comment by pryrt** [comment]
closed by #596

**Comment by alankilborn** [comment]
As this Community posting is cited in the user manual:  https://community.notepad-plus-plus.org/topic/19632 , let's fix some errors in that posting:

* The FIRST match in the posting for `The first found pattern AB+(*SKIP)CD matches ABB but cannot match CD` should be `The first found pattern AB+(*COMMIT)CD matches ABB but cannot match CD`

* In the text `(*SKIP) Behaves the same as (*PRUNE) except that it is assumed that no match`, (*PRUNE) should be highlighted as (*SKIP) is

* `Usually, the (*PRUNE**) verb is simply an alternative` should be `Usually, the (*PRUNE) verb is simply an alternative`

* `Sometimes, the use of the (SKIP) backtracking control verb is even better !` should be `Sometimes, the use of the (*SKIP) backtracking control verb is even better !`

* `by modern regex engines, whose our Boost regex engine !` should be `by modern regex engines, including our Boost regex engine !`

* `match of Z is discarded, due to the (ACCEPT) verb` should be `match of Z is discarded, due to the (*ACCEPT) verb`

* `(SKIP)` should be `(*SKIP)`

* this is rather messed up:  `A generic regex would be : What_I_don’t want(*SKIP)(*FAIL)|What_I_want    or    What_I_don’t want(*SKIP)(*F)|What_I_want` ; suggest change to: `A generic regex would be : What_I_do_not_want(*SKIP)(*FAIL)|What_I_want    or    What_I_do_not_want(*SKIP)(*F)|What_I_want` (both removes the inappropriate extra spacing, and the apostrophe, both of which just make this tougher to read)

* The FIRST match of `So, the first found pattern AB+(*PRUNE)CD matches ABBBB but cannot match CD` should be `So, the first found pattern AB+(*SKIP)CD matches ABBBB but cannot match CD`

* `This means that, if at current position in string, the regex engine can match the part before (*SKIP) but cannot match the part after (*SKIP), as any backtracking is canceled to the left of (*SKIP), the regex engine discards any further search and the current match attempt just fails. So the regex engine must advance to the location where the zero-width (*SKIP) verb occurs, for a new match attempt !` is better said as `This means that, if at current position in string, the regex engine can match the part before (*SKIP) but cannot match the part after (*SKIP), as any backtracking is canceled to the left of (*SKIP), the regex engine discards any further search and the current match attempt just fails. So the regex engine must advance to the location in the string corresponding to where (*SKIP) was matched, for the next new match attempt !`

**Comment by pryrt** [comment]
Okay, I think I got those all correctly changed.
