### ISSUE TITLE
documented session.xml location seems to be backwards

### ISSUE THREAD

**Issue by bugnaturalist** [notepad-plus-plus/npp-usermanual#622]
In the User Manual section Configuration File Details (https://npp-user-manual.org/docs/config-files/), the section on session.xml seems to document the location backwards from actuality, probably due to a copy and paste that wasn't customized sufficiently.  The doc says it is located in the installation directory and I did not find it there.  Logically it belongs in AppData\Notepad++ because it is user specific, and I did find it there on my computer.

**Comment by alankilborn** [comment]
For the "portable" version it is indeed in the installation directory, if by that you mean the directory in which `notepad++.exe` lives.

**Comment by bugnaturalist** [comment]
"In the installation folder" would be consistent with the section titled Configuration Files Location. That section initially talks about per-user configuration files, and neglects to mention session.xml.  The heading for the section I'm referencing is "session.xml"

**Comment by pryrt** [comment]
I agree: the `session.xml` bullet at the end is wrong, because it definitely uses AppData under a normal installation.  But `session.xml` is weird, in that while it defaults to AppData and it follows the `-settingsDir` command-line option, if you are using a cloud folder, it gets the `session.xml` from the installed directory, _not_ the cloud directory.

I will fix the description

**Comment by pryrt** [comment]
Following [this link](https://github.com/notepad-plus-plus/npp-usermanual/pull/623/files#diff-474ecc311aec5cc7a9aee3faadb7b570f9fa3464f9aa7cfbfc2856cf1621936a) will show the changes made to fix/improve the `session.xml` description
