### ISSUE TITLE
Add new plugin command description: NPPM_SETUNTITLEDNAME

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/npp-usermanual#679]
References:

* https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8916
* https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b3daf0a98220ffc6e206133aa645d5a2d1d63a4f

Documentation should (possibly) mention that with this new plugin command, an old undocumented means of renaming an untitled tab's name was removed.

**Comment by pryrt** [comment]
> Documentation should (possibly) mention that with this new plugin command, an old undocumented means of renaming an untitled tab's name was removed.

I don't think documentation should mention changes regarding INTERNAL messages -- the whole reason they are "internal" is because they weren't meant to be used publicly, and they may change or be removed without announcement or documentation.  I added a note to that effect in the manual.

But since the code comment in the deleted function mentioned `netnote plugin` explicitly, I searched out that plugin and created https://github.com/chcg/NppDocShare/issues/10 -- hopefully @chcg can get that updated and submitted to nppPluginList before 8.6.9-RC1
