### ISSUE TITLE
Documentation enhancement to describe the process of aborting/exiting column mode via the Esc key

### ISSUE THREAD

**Issue by turonosaurus** [notepad-plus-plus/npp-usermanual#703]
I decided to investigate my inability to control / figure out how, in Notepad++, to control where the cursor lands when you're using Column mode and you hit your Esc key to exit/abort column mode.  It seemed to me like usually it would fall **_after_** the selection but **_sometimes_** at the beginning, but I couldn't control it or predict **_where_** it was going to land.  After searching online and in the Notepad++ documentation on this and finding nothing, I was about to submit a Bug report and, as I was thinking about the steps to reproduce it hit me!  Where the cursor lands is dependent upon the direction you are going **_when you first make_** your selection at the point **_when you activate_** column mode.
- If I hold Alt+C and hit my **_up_** arrow key to select in the upwards direction, later when I hit Esc the cursor lands **_at the beginning_** of the selection.
- In contrast if I hold Alt+C and hit my **_down_** arrow key to select in the upwards direction, later when I hit Esc the cursor lands **_at the end_** of the selection.

With this realization I can see that it is working as designed - however - it would be nice if Notepad++'s documentation had explicitly spelled this out for me - and for the community of users.  I would think that [this "Selection modes & Column Editor" article](https://npp-user-manual.org/docs/editing/) should get updated appropriately to convey this information.

**Comment by pryrt** [comment]
`Alt+C` doesn't do column selection; `Alt+C` is the column editor (for adding numbering to a column).  Column-mode selection is done by holding down `Alt` while dragging, or holding down `Alt` while `Shift+Arrow` to select.

So, if you mean that "if you have a column selection (whether by `Alt+MouseDrag` or `Alt+Shift+Arrow`), then hitting `ESC` will leave column-selection mode and the typing caret will be at the last corner of your selection.  Thus, if you did your column selection from upper-left to lower-right, the caret will be in the lower right after the `ESC`; if you did your column selection from upper-right to lower-left, the caret will be in the lower left after the `ESC`; if you do the column selection from lower-left to upper-right, then the caret will end up in the upper right after the `ESC`; and if you do the column selection from lower-right to upper-left, then the caret will end up in the upper-left after `ESC`." -- I wouldn't have thought that needed explaining, since the typing caret ends up a the whichever side of the selection you ended the selection at for normal (non-column) selections as well... but if you think I need to make that clear, I can.
